# -- Deploy Argo CD Applications within this helm release
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
applications:
 - name: demo
   namespace: argocd
   additionalLabels: {}
   additionalAnnotations: {}
   project: default
   source:
     repoURL: placeholder
     targetRevision: HEAD
     path: demoapp
     directory:
       recurse: true
   destination:
     server: https://kubernetes.default.svc
     namespace: application
   syncPolicy:
     automated:
       prune: false
       selfHeal: false
   revisionHistoryLimit: null
   ignoreDifferences:
   - group: apps
     kind: Deployment
     jsonPointers:
     - /spec/replicas
   info:
   - name: url
     value: https://argoproj.github.io/
