# -- Deploy Argo CD Applications within this helm release
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
applications:
  bookapp:
    namespace: argocd
    project: default
    source:
      repoURL: ${repoURL}
      targetRevision: ${targetRevision}
      path: "bookapp"
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: "application"
    syncPolicy:
      automated:
        prune: false
        selfHeal: false
      syncOptions:
      - CreateNamespace=true
    revisionHistoryLimit: null
    ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
      - /spec/replicas
    info:
    - name: url
      value: https://argoproj.github.io/
