apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-action-runner
spec:
  replicas: 1
  template:
    spec:
      repository: {{ .Values.projectrepo }}
      labels:
        - {{ .Values.tag_env }}